### ISSUE TITLE
[QUESTION] How does it do with shaders? Does the loaded chunk also use shaders?

### ISSUE THREAD

**Issue by skyshade121** [TrattMods/LiterallyChunkLoader-1.15#10]
If the title is confusing:
*with shaders*
Let's say I placed a loader on my iron farm.
And I go at least 500+ blocks away
Does the loaded chunk(Iron farm) use the shaders?

**Comment by tratteo** [comment]
Shaders are just a way of rendering, if you are 500 blocks away, that area is not rendering at all

**Comment by skyshade121** [comment]
> Shaders are just a way of rendering, if you are 500 blocks away, that area is not rendering at all

Wow! Thank you for your fast reply!
