### ISSUE TITLE
Crush on world Loading 1.17.1

### ISSUE THREAD

**Issue by oBoLLl** [TrattMods/LiterallyChunkLoader-1.15#12]
Good day! At the start of any world, the new / old crashes before loading the world. Modpack - Better Minecraft fabric v.11. Accordingly, the modpack without your chunkloader starts and works stably.

Crashreport [https://paste.gg/p/anonymous/6920b6d9f4ff4fe78306d344d16e415d](url)

Аll the same, I would like to enjoy the chunkloader when moving to fabric. Thanks!

**Comment by tratteo** [comment]
Seems the duplicate o issue: https://github.com/TrattMods/LiterallyChunkLoader-1.15/issues/11. It seems some other mods interfere with the TickManager of LiterallyChunkLoader and causes the crash
