### ISSUE TITLE
1.17.1 issue

### ISSUE THREAD

**Issue by cosmoderp** [TrattMods/LiterallyChunkLoader-1.15#8]
its causing a crash in 1.17.1.  tested without this mod and everything booted fine. so something I guess changed that caused this.
crash log included
[crash-2021-07-09_18.19.27-client.txt](https://github.com/TrattMods/LiterallyChunkLoader-1.15/files/6794139/crash-2021-07-09_18.19.27-client.txt)

**Comment by ErickDiniz** [comment]
because it doesn't have for version 1.17.1 yet

**Comment by nthnlws** [comment]
Also crashing on 1.17.1 using the 2.0.3 version of the mod. Crash report uploaded below.
[crash-2021-07-28_01.38.18-server.txt](https://github.com/TrattMods/LiterallyChunkLoader-1.15/files/6890853/crash-2021-07-28_01.38.18-server.txt)

**Comment by nthnlws** [comment]
Found the problem. The bundled lib "LibGui" is causing the chunk loading mod to crash. Was able to fix by downloading the latest 1.17.1 version on the GitHub. https://github.com/CottonMC/LibGui/releases

**Comment by tratteo** [comment]
I just released the version for 1.17.1 on CurseForge in which the LibGui 1.17.1 is bundled. Closing this! Thanks for the reports
